#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd ${DIR}/mingw-w64-ruby-gdbm
MINGW_INSTALLS=mingw64 makepkg-mingw -sLf --skippgpcheck

cd ${DIR}/mingw-w64-ruby-libyaml
MINGW_INSTALLS=mingw64 makepkg-mingw -sLf --skippgpcheck

cd ${DIR}/mingw-w64-ruby-openssl
MINGW_INSTALLS=mingw64 makepkg-mingw -sLf --skippgpcheck
